init->* |
|
  self setGraphics: 'GR/MarkerDrug/Idle' .
  max_ammo _ 150 . 
  ammo _ 30 .
  x _ 0 .
  y _ 300 .
  xoff _ 0 .
  yoff _ 0 .
  timeout _ 0 .
  state _ 'Idle' .

  inventory_item _ CUIGridItem new .
  inventory_item setGraphics: 'GR/MarkerDrug/Idle' .
  inventory_item setCount: ammo .
  inventory_item setItem: self .
  inventory_item onLeftUp: [
    #hand_item _ self .
  ] .
  #world getPlayer addInventoryItem: inventory_item .

  ^ self