afterRestore->* |
  old_items=CFrogArray
|
  piss_stream setFrom: self.
  
  template _ #world getThingTemplate: template_name. 
  chat_bot _ #world getChatBot: chat_bot_name .

'Re-add the items to the player(update graphics and put in inentory grids).' .
  old_items _ items .
  items _ #() .
  old_items do: [:i=CHandItem|
    i addToPlayerAgain: self .
    i -> is_equiped ifTrue: [
      #hand_item _ i .
    ] .
  ] .