init ->CPlayer | |
  #world addThing: self .
  #world -> player _ self .
  items _ #() .
  health _ 75 .
  no_draw _ 1 .
  shell_casings _ #() .
  self makeUI .
  piss_stream _ CPissStream new .
  piss_stream ->from _ self .
  #hand_item _ CGun1 new .

  CFrogDick new .
  CKnife new .
  CTalker  new .
  CMarkerDrugItem new .

  CNumchucks new .

  quest_flags _ #() .
  quest_seen_responses _ #().

  0 to: 16 do: [:idx=CFrogNum|
    CWorldEditBlock new: idx .
  ].

  ^ self
