meleeAttackWithDamage: damage=CFrogNum ->*
|
  best_target=C3DThing
  targets=CFrogArray
  best_angle=CFrogNum
  tmp=CFrogNum
  rotate_weight=CFrogNum
|
  'Todo smooth face target' .
  targets _ #world getThingsInRadiusFromX: x fromY: y withRadius: 2 .
  best_angle _ 3.14 / 4  .
  targets do: [:target=C3DThing |
    tmp _ self angleBetween: target .
    ((best_angle > tmp and: self ~= target) and:
      target->health > 0 ) ifTrue: [
      best_angle _ tmp .
      best_target _ target .
      target show .
    ] .
  ] .
  
  (best_target hasClass: C3DThing) ifTrue: [
    rotate_weight _ 1 / 3 .
     'Weighted averegate' .
     angle _ best_target->x - x arg: best_target->y - y . 
     #world ->is_client ifTrue: [
       #client sendAttackOfThing: best_target withDamage: damage .
     ] ifFalse: [
       best_target damage: damage from: self
     ] .
  ].


