onClickAtX: x=CFrogNum atY: y=CFrogNum ->*
|
  w=CFrogNum
  h=CFrogNum
|
  w _ 0 .
  h _ 0 .
  sub_elems do: [:e=CUIElem |
    w _ w max: (e getX + e getWidth) .
    h _ h max: (e getY + e getHeight) .
  ] .
  (self getWidth - 8) <= x ifTrue: [
    y_scroll _ y / self getHeight * h.
    y_scroll < 0 ifTrue: [
      y_scroll _ 0
    ].
  ].
  (self getHeight - 8) <= y ifTrue: [
    x_scroll _ x / self getWidth * w.
    x_scroll < 0 ifTrue: [
      x_scroll _ 0
    ].
  ].