init | |
  self setGraphics: 'GR/GUN1/IDLE' .
  self setMaxAmmo: 30 .
  ammo _ 30 .
  x _ 0 .
  y _ 300 .
  xoff _ 0 .
  yoff _ 0 .
  timeout _ 0 .
  inventory_item _ CUIGridItem new .
  inventory_item setGraphics: 'GR/GUN1/IDLE' .
  inventory_item setCount: ammo .
  inventory_item setItem: self .
  inventory_item onLeftUp: [
    #hand_item _ self .
  ].
  #world getPlayer addInventoryItem: inventory_item.
  ^ self
