lookForTarget -> C3DThing
|
|
  (#world getThingsInRadiusFromX: x fromY: y withRadius: 32) do:[:t=C3DThing|
    ((t hasClass: CPlayer) or: (t hasClass: CSmartEnemy)) ifTrue: [
      ((self canSeeThing: t) and: t->health > 0) ifTrue: [
        t ~= self ifTrue: [
          team ifTrue: [
             team ~= t->team ifTrue: [
               ^ t
             ].
          ] ifFalse: [
            ^ t
          ]
        ]
      ] .
    ]
  ] .
  ^ 0 .
