moveGoesOverEdge: dist=CFrogNum atAngle: a=CFrogNum ->CFrogNum
|
  xx=CFrogNum
  yy=CFrogNum
  zz=CFrogNum
  tile=CFrogNum
|
  dist _  (3.5 * dist) + template->radius.
  xx _ x + (dist * a cos) .
  yy _ y + (dist * a sin) .

  tile _ #world getTileAtX: xx   atY: yy  atZ: z - 1 .
  tile ~= 0 ifTrue: [
    tile _ #world getTileAtX: xx   atY: yy  atZ: z - 2 .
'Hole in ground ' .
    ^ tile = 0 .
  ] .
  ^ 0 
