moveGoesOverEdge: dist=CFrogNum atAngle: a=CFrogNum ->CFrogNum
|
  xx=CFrogNum
  yy=CFrogNum
  zz=CFrogNum
  hole_depth=CFrogNum
|
'3* becuase we only update every 3 frames(physics moves for us)' .
  zz _ #world getPlatformHeightAtX: x atY: y .
  dist _  (3.5 * dist) + template->radius + 64 .
  xx _ x + (dist * a cos) .
  yy _ y + (dist * a sin) .

  hole_depth _ #world getPlatformHeightAtX: xx atY: yy .
  (zz - hole_depth) > 1.5 ifTrue: [
    ^ 1 .
  ]. 
  ^ 0 