init | dick |
  self setGraphics: 'GR/Dick/DICK' .
  ammo _ 100 .
  x _ 0 .
  y _ 300 .
  xoff _ 0 .
  yoff _ 0 .
  timeout _ 0 .
  inventory_item _ CUIGridItem new .
  inventory_item setGraphics: 'GR/Dick/DICK' .
  inventory_item setCount: ammo .
  inventory_item setItem: self .
  dick _ self .
  inventory_item onLeftUp: [:x=CFrogNum :y=CFrogNum |
    #hand_item _ dick .
  ].
  #world getPlayer addInventoryItem: inventory_item.
  ^ self
