screenRayHitsTarget: t=C2DThing
  atAngle: a=C2DThing
  withAutoAim: mul=C2DThing
  -> CFrogNum
| 
  xx=CFrogNum
  yy=CFrogNum 
  dist=C2DThing
  dist_scale=C2DThing
  tolerance=C2DThing
|
  (self canSeeThing: t ) ifFalse: [
    ^ 0
  ] .
  'See 3D.HC' .
  tolerance _ ( 3.14 / 8 ) * mul.
  xx _ t->x - self->x .
  yy _ t->y - self->y .
  a _ ((xx arg: yy ) - a) cos arccos.
  a > 3.14 ifTrue: [
    a _ a - 3.14 .
  ] .
  a abs < tolerance ifTrue: [
    ^ 1
  ] .
  ^ 0.