screenRayHitsTarget: t=C2DThing
  atAngle: a=C2DThing
  withAutoAim: mul=C2DThing
  -> CFrogNum
| 
  dist=C2DThing
  dist_scale=C2DThing
  tolerance=C2DThing
|
  (self canSeeThing: t ) ifFalse: [
    ^ 0
  ] .
  'See 3D.HC' .
  dist_scale _ 128 * 480 .
  dist _ ( (x - t xPos ) squared + (y - t yPos ) squared ) sqrt .
  dist _ dist_scale / ( dist + .1 ) .
  tolerance _ ( 3.14 / 4 / 640 ) * dist * mul.
  (self angleBetween: t) < tolerance ifTrue: [
    ^ 1
  ] .
  ^ 0. 