init | |
  self setGraphics: 'GR/Numchucks/Idle' .
  max_ammo _ 0 . 
  ammo _ 0 .
  x _ 0 .
  y _ 300 .
  xoff _ 0 .
  yoff _ 0 .
  timeout _ 0 .
  inventory_item _ CUIGridItem new .
  inventory_item setGraphics: 'GR/Numchucks/Idle' .
  inventory_item setCount: 0 .
  inventory_item setItem: self .
  inventory_item ->name _
'Numchucks
Ninja some asswipes
kung-fu style
' .
  inventory_item onLeftUp: [
    #hand_item _ self .
  ].
  #world getPlayer addInventoryItem: inventory_item.
  ^ self