init: idx=CFrogNum ->* | |
  max_ammo _ 0 . 
  ammo _ 0 .
  x _ 0 .
  y _ 300 .
  xoff _ 0 .
  yoff _ 0 .
  timeout _ 0 .
  inventory_item _ CUIGridItem new .
  inventory_item setCount: ammo .
  inventory_item setItem: self .
  inventory_item onLeftUp: [
    #hand_item _ self .
  ] .

 'SetBlockIdx sets greaphgics for us'.
  (self setBlockIndex: idx) ifTrue: [
    #world getPlayer addInventoryItem: inventory_item .
    ^ self
  ] .
  ^ 0 
