init | |
  walk_template_name _ 'CCyberPoop'.
  dying_template_name _ 'CCyberPoop/Dead'.
  attack_template_name _ 'CCyberPoop/Fire'.
  item_capacity _ 4 .
  speed _ 1 / 2 /10 .
  health _ 250 .
  has_items _ #(
    #(CRocketLauncher 50)
    #(CShitItem 15)
  ).
  current_item_pair _ has_items first .
  can_use_items _ #(CRocketLauncher CShitItem).
  blood_color _ #color_BROWN .
  #world addThing: self .

  ^ self 