initFromStream:s=CNetStream ->C3DWorldClient 
|
  recur=CFrogBlock
  now=CFrogNum
|
  sock _ CAsyncStream newFromStream s .
  last_response_tS _ CFrogTime now asSeconds .
  
  recur _ [
    sock readU32WithCallback:[:w* :cnt=CFrogNum|
     last_response_tS _ CFrogTime now asSeconds .
     sock readBytes: cnt withCallback: [:w* :buf=CFrogStr|
        self handleMessage: buf .
        'Re-arm callbackcs' .
        recur value .
      ].
    ] .
  ]
  #client _ self .
   recur value .
  ^ self
