addWallStain: s=CWallStain ->* | new=CWallStain |
  wall_stains do: [:s2=CWallStain |
    (s->tile->x = s2->tile->x and: s->tile->y = s2->tile->y) ifTrue: [
      s getSide = s2 getSide ifTrue: [
        new _ s2 mergeWith: s .
        wall_stains remove: s2 .
        wall_stains add: new .
        ^ 1 .
      ]
    ] .
  ].
  wall_stains size > 32 ifTrue: [
    wall_stains removeAt: 0 
  ] .  
  wall_stains add: s