init | gx=CFrogNum gy=CFrogNum col=CFrogArray |
  #world _ self .
  wall_stains _ #() .
  floor_stains _ #() .
  things _ #() .
  grid _ # () .
  gravity _ 3 / 30 .
  tile_templates _ CFrogDictionary new .
  thing_templates _ CFrogDictionary new .
  'the world_handle field is set in 3D.HC'. 
  gx _ (self width + 15 ) / 16 .
  gy _ (self height + 15 ) / 16 .


  0 to: gx do: [
    col _ # () .
    0 to: gy do: [
      col add: #() 
    ].
    grid add: col .
  ] .
  ^ self
