doorInRadius: r=CFrogNum 
  atX: x=CFrogNum
  atY: y=CFrogNum
  atAngle: a=CFrogNum 
    ->CDoor
|
|
  -1 to: 2 do:[:xoff=CFrogNum|
    -1 to: 2 do:[:yoff=CFrogNum|
      ((grid at: x / 16 + xoff)
        at: y /16 + yoff) do:[:d=CDoor|
         (d hasClass: CDoor) ifTrue: [    
           ((d ->x + .5 - x ) squared + (d->y + .5 - y) squared ) sqrt < 2 ifTrue: [
            ^ d
          ]
        ]
      ]
    ]
  ]. 
  ^ 0 
