getPlatformHeightAtX: x=CFrogNum atY: y=CFrogNum ->CFrogNum
|base=CFrogNum|
  base _ self tileHeightAtX: x / 128 atY: y / 128 .
  ((grid at: x / 128 / 16) at: y / 128 / 16 ) do:[:d=CDoor|
    (d hasClass: CDoor) ifTrue: [
'+.5 means ccnter' .
'< .5 means halfway from center' .
      (((x / 128) - (d->x + .5)) abs < .5  and: ((y / 128) - (d->y + .5 )) abs < .5 ) ifTrue: [
        ^ base + (d->height * d->percent )
      ] .
    ]
  ] .
  ^ base  