initGrid ->* 
|
 gx=CFrogNum
 gy=CFrogNum
 col=CFrogArray 
|
'INITGRID ' show.
self width show .
  'the world_handle field is set in 3D.HC'. 
  gx _ (self width + 16 ) / 16 .
  gy _ (self height + 16 ) / 16 .

  gx show .
  gy show .

  grid _ #() .

  0 to: gx do: [:a=CFrogNum|
'a 'show.
     a show .
    col _ # () .
    0 to: gy do: [:b=CFrogNum|
'b 'show.
     b show .
      col add: #() 
    ].
    grid add: col .
  ] .
