update ->* | p=CPlayer |
  p _self getPlayer .
  things do: [:t* |
    self removeFromGrid: t .
    t update .
    p = t ifTrue: [
      ((grid at: (p ->x / 128 / 16) ) at: p ->y / 128 / 16) do: [:pu* |
        (pu hasClass: CPickup ) ifTrue: [
           (pu hitsThing: p ) ifTrue: [ pu addToPlayer: p ]
        ].
      ]
    ] .
    self updateThingPos: t
  ] .

  'UI and stuf' .
  (#hand_item hasClass: CHandItem) ifTrue: [
    #hand_item animate
  ] .